# Generated by Django 4.2.7 on 2024-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
