# Generated by Django 4.2.7 on 2024-04-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_auto_20240411_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='link',
        ),
    ]
