# Generated by Django 4.2.7 on 2024-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_remove_song_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
