# Generated by Django 4.2.11 on 2024-03-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('song_name', models.CharField(max_length=35)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
