# Generated by Django 5.0.3 on 2024-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
