# Generated by Django 4.2.7 on 2024-04-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Nie rozpatrzony', 'Nie rozpatrzony'), ('Przyjęty', 'Przyjęty'), ('Odrzucony', 'Odrzucony')], default='Nie rozpatrzony', max_length=15),
        ),
    ]
