# Generated by Django 4.2.7 on 2024-04-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_request_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-status']},
        ),
    ]
