# Generated by Django 4.2.11 on 2024-04-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='surname',
        ),
    ]
