# Generated by Django 4.2.7 on 2024-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='surname',
        ),
        migrations.AlterField(
            model_name='artist',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
    ]
