# Generated by Django 4.2.7 on 2024-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_name_remove_artist_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster/'),
        ),
    ]
