# Generated by Django 4.2.7 on 2024-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
