# Generated by Django 4.2.11 on 2024-05-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_artist_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='poster',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_poster',
            field=models.ImageField(blank=True, null=True, upload_to='artist_posters/'),
        ),
    ]
